language: python

python:
  - "3.6"
  - "nightly"

install:
  - pip install -e .
  - pip install -e .[test]
  - pip install -e .[cov]

script:
  - pytest --cov=./

after_success:
  - codecov

notifications:
  email: false