"""create tables

Revision ID: 5d2e2a345bed
Revises: 
Create Date: 2016-09-20 03:24:59.799784

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5d2e2a345bed'
down_revision = None
branch_labels = None
depends_on = None

def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('record_nwp_cma20n03',
    sa.Column('record_id', sa.Integer(), nullable=False),
    sa.Column('repo_id', sa.Integer(), nullable=True),
    sa.Column('version_id', sa.Integer(), nullable=True),
    sa.Column('line_no', sa.Integer(), nullable=True),
    sa.Column('record_type', sa.String(length=100), nullable=True),
    sa.Column('record_date', sa.Date(), nullable=True),
    sa.Column('record_time', sa.Time(), nullable=True),
    sa.Column('record_command', sa.String(length=100), nullable=True),
    sa.Column('record_fullname', sa.String(length=200), nullable=True),
    sa.Column('record_additional_information', sa.Text(), nullable=True),
    sa.Column('record_string', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('record_id')
    )
    op.create_table('record_nwp_pd_cma20n03',
    sa.Column('record_id', sa.Integer(), nullable=False),
    sa.Column('repo_id', sa.Integer(), nullable=True),
    sa.Column('version_id', sa.Integer(), nullable=True),
    sa.Column('line_no', sa.Integer(), nullable=True),
    sa.Column('record_type', sa.String(length=100), nullable=True),
    sa.Column('record_date', sa.Date(), nullable=True),
    sa.Column('record_time', sa.Time(), nullable=True),
    sa.Column('record_command', sa.String(length=100), nullable=True),
    sa.Column('record_fullname', sa.String(length=200), nullable=True),
    sa.Column('record_additional_information', sa.Text(), nullable=True),
    sa.Column('record_string', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('record_id')
    )
    op.create_table('record_nwp_qu_cma18n03',
    sa.Column('record_id', sa.Integer(), nullable=False),
    sa.Column('repo_id', sa.Integer(), nullable=True),
    sa.Column('version_id', sa.Integer(), nullable=True),
    sa.Column('line_no', sa.Integer(), nullable=True),
    sa.Column('record_type', sa.String(length=100), nullable=True),
    sa.Column('record_date', sa.Date(), nullable=True),
    sa.Column('record_time', sa.Time(), nullable=True),
    sa.Column('record_command', sa.String(length=100), nullable=True),
    sa.Column('record_fullname', sa.String(length=200), nullable=True),
    sa.Column('record_additional_information', sa.Text(), nullable=True),
    sa.Column('record_string', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('record_id')
    )
    op.create_table('record_nwp_qu_cma20n03',
    sa.Column('record_id', sa.Integer(), nullable=False),
    sa.Column('repo_id', sa.Integer(), nullable=True),
    sa.Column('version_id', sa.Integer(), nullable=True),
    sa.Column('line_no', sa.Integer(), nullable=True),
    sa.Column('record_type', sa.String(length=100), nullable=True),
    sa.Column('record_date', sa.Date(), nullable=True),
    sa.Column('record_time', sa.Time(), nullable=True),
    sa.Column('record_command', sa.String(length=100), nullable=True),
    sa.Column('record_fullname', sa.String(length=200), nullable=True),
    sa.Column('record_additional_information', sa.Text(), nullable=True),
    sa.Column('record_string', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('record_id')
    )
    op.create_table('record_nwp_sp_cma20n03',
    sa.Column('record_id', sa.Integer(), nullable=False),
    sa.Column('repo_id', sa.Integer(), nullable=True),
    sa.Column('version_id', sa.Integer(), nullable=True),
    sa.Column('line_no', sa.Integer(), nullable=True),
    sa.Column('record_type', sa.String(length=100), nullable=True),
    sa.Column('record_date', sa.Date(), nullable=True),
    sa.Column('record_time', sa.Time(), nullable=True),
    sa.Column('record_command', sa.String(length=100), nullable=True),
    sa.Column('record_fullname', sa.String(length=200), nullable=True),
    sa.Column('record_additional_information', sa.Text(), nullable=True),
    sa.Column('record_string', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('record_id')
    )
    op.create_table('record_nwp_vfy_cma18n01',
    sa.Column('record_id', sa.Integer(), nullable=False),
    sa.Column('repo_id', sa.Integer(), nullable=True),
    sa.Column('version_id', sa.Integer(), nullable=True),
    sa.Column('line_no', sa.Integer(), nullable=True),
    sa.Column('record_type', sa.String(length=100), nullable=True),
    sa.Column('record_date', sa.Date(), nullable=True),
    sa.Column('record_time', sa.Time(), nullable=True),
    sa.Column('record_command', sa.String(length=100), nullable=True),
    sa.Column('record_fullname', sa.String(length=200), nullable=True),
    sa.Column('record_additional_information', sa.Text(), nullable=True),
    sa.Column('record_string', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('record_id')
    )
    op.create_table('repo',
    sa.Column('repo_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('repo_name', sa.String(length=45), nullable=True),
    sa.Column('repo_type', sa.String(length=45), nullable=True),
    sa.PrimaryKeyConstraint('repo_id')
    )
    op.create_table('repo_version',
    sa.Column('repo_version_id', sa.Integer(), nullable=False),
    sa.Column('repo_id', sa.Integer(), nullable=True),
    sa.Column('version_id', sa.Integer(), nullable=True),
    sa.Column('version_name', sa.String(length=100), nullable=True),
    sa.Column('version_location', sa.String(length=200), nullable=True),
    sa.Column('head_line', sa.Text(), nullable=True),
    sa.Column('collector_id', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('repo_version_id')
    )
    op.create_table('sms_repo',
    sa.Column('sms_repo_id', sa.Integer(), nullable=False),
    sa.Column('repo_id', sa.Integer(), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('repo_name', sa.String(length=45), nullable=True),
    sa.Column('repo_location', sa.String(length=100), nullable=True),
    sa.Column('current_version_id', sa.Integer(), nullable=True),
    sa.Column('repo_description', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('sms_repo_id')
    )
    op.create_table('user',
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('user_name', sa.String(length=45), nullable=True),
    sa.PrimaryKeyConstraint('user_id')
    )
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('user')
    op.drop_table('sms_repo')
    op.drop_table('repo_version')
    op.drop_table('repo')
    op.drop_table('record_nwp_vfy_cma18n01')
    op.drop_table('record_nwp_sp_cma20n03')
    op.drop_table('record_nwp_qu_cma20n03')
    op.drop_table('record_nwp_qu_cma18n03')
    op.drop_table('record_nwp_pd_cma20n03')
    op.drop_table('record_nwp_cma20n03')
    ### end Alembic commands ###
